### PR TITLE
Fix #25 False positive for backgroud-position, using multiple backgro…

### LINKED ISSUE #25: Update background-position validator (multiple backgrounds)
Hi!

I have some rules in a class, kind of like this:

    background-image: url("/pic1.png"), url("/pic2.png");
    background-position: center center, top left;

It got flagged as as an error:
Update the invalid value of property "background-position". Expected format: [ <length> | <percentage> | top | bottom | center | left | right ]+

I was following this page on MDN to implement the multiple background images:
https://developer.mozilla.org/en/docs/Web/CSS/CSS_Background_and_Borders/Using_CSS_multiple_backgrounds

I'm guessing the rule isn't handling multiple values for background-position correctly?

### PR DESCRIPTION
**Pull request by racodond**
…unds

### CODE REVIEW

File: css-frontend/src/main/java/org/sonar/css/model/property/validator/property/background/BackgroundPositionValidator.java [hunk 1]
```diff
@@ -0,0 +1,106 @@
...
+  }
+
+  private boolean validateTwoElements(List<Tree> valueElements) {
+    return (isLengthOrPercentage(valueElements.get(0))
+      || new IdentifierValidator("left", "center", "right").isValid(valueElements.get(0)))
+      && (isLengthOrPercentage(valueElements.get(1))
+      || new IdentifierValidator("top", "center", "bottom").isValid(valueElements.get(1)));
+  }
+
+  private boolean validateThreeOrFourElements(List<Tree> valueElements) {
```
Comment (racodond) [inline css-frontend/src/main/java/org/sonar/css/model/property/validator/property/background/BackgroundPositionValidator.java:65]: CRITICAL Refactor this method to reduce its Cognitive Complexity from 17 to the 15 allowed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS3776)

File: css-frontend/src/main/java/org/sonar/css/model/property/validator/property/background/BackgroundPositionValidator.java [hunk 2]
```diff
@@ -0,0 +1,106 @@
...
+  }
+
+  @Override
+  public String getValidatorFormat() {
+    return "[ [ left | center | right | top | bottom | <length> | <percentage> ] | [ left | center | right | <length> | <percentage> ] [ top | center | bottom | <length> | <percentage> ] | [ center | [ left | right ] [ <length> | <percentage> ]? ] && [ center | [ top | bottom ] [ <length> | <percentage>]? ] ]";
+  }
+
+  private boolean validateOneElement(Tree valueElement) {
+    return isLengthOrPercentage(valueElement)
+      || new IdentifierValidator("left", "right", "center", "top", "bottom").isValid(valueElement);
```
Comment (racodond) [inline css-frontend/src/main/java/org/sonar/css/model/property/validator/property/background/BackgroundPositionValidator.java:55]: CRITICAL Define a constant instead of duplicating this literal "center" 4 times. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1192)
CRITICAL Define a constant instead of duplicating this literal "bottom" 3 times. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1192)
CRITICAL Define a constant instead of duplicating this literal "right" 3 times. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1192)

File: css-frontend/src/main/java/org/sonar/css/model/property/validator/property/background/BackgroundPositionValidator.java [hunk 3]
```diff
@@ -0,0 +1,106 @@
...
+    }
+
+    for (int i = 1; i < valueElements.size(); i++) {
+      if (isLengthOrPercentage(valueElements.get(i))
+        && (isLengthOrPercentage(valueElements.get(i - 1)) || centerValidator.isValid(valueElements.get(i - 1)))) {
+        return false;
+      }
+    }
+
+    if (isLengthOrPercentage(valueElements.get(0))) {
```
Comment (racodond) [inline css-frontend/src/main/java/org/sonar/css/model/property/validator/property/background/BackgroundPositionValidator.java:94]: MINOR Replace this if-then-else statement by a single return statement. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1126)

**Comment by racodond** [comment]
SonarQube analysis reported 5 issues
* ![CRITICAL][CRITICAL] 4 critical
* ![MINOR][MINOR] 1 minor

Watch the comments in this conversation to review them.

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'
